### ISSUE TITLE
I deal with the files in markdown format exactly according to the webpack settings of UIV,Markdown files can really be previewed, but the code has not been highlighted. Is I missing any configuration? Thanks~

### ISSUE THREAD

**Issue by zzhf** [wxsms/vue-md-loader#1]

**Comment by wxsms** [comment]
You need to include one of the `highlight.js` css files into your project.

for example: `highlight.js/styles/github-gist.css`

**Comment by wxsms** [comment]
Closing. If this doesn't work for you, feel free to continue discussing.
