### ISSUE TITLE
plugin.apply is not a function

### ISSUE THREAD

**Issue by Blubiubiu** [wxsms/vue-md-loader#239]
webpack:  v5.52.0
vue-loader:  v15.9.8
![image](https://user-images.githubusercontent.com/16317188/132681250-aa6ac842-5d2e-4f72-a1b3-3e2d7acc10a5.png)
当构建项目时
![image](https://user-images.githubusercontent.com/16317188/132681301-4d0c09dd-1a72-458c-a33d-c7a1d97d6468.png)

**Comment by wxsms** [comment]
the example folder is using exactly same version of webpack and vueloader. and it works fine.

**Comment by Blubiubiu** [comment]
but now i have another problem.
![image](https://user-images.githubusercontent.com/16317188/132813104-42eccd9d-990c-4f47-8f39-d866a13016be.png)
may u give me a demo for vue-loader@15.X.X

**Comment by wxsms** [comment]
https://github.com/wxsms/vue-md-loader/tree/master/example
this repo's example is.

**Comment by Blubiubiu** [comment]
i use it like yours, but also not work
![image](https://user-images.githubusercontent.com/16317188/132819453-40a1d3b0-b093-4c20-9fe5-a48bfb4b157e.png)

**Comment by Blubiubiu** [comment]
`<script>
    export default {
        data() {
            return {
            };
        },
        methods: {
        }
    }
</script>

<style>

</style>

## timeline

### 基本用法

```
:::

### 更改时间点颜色

::: demo 'color'属性可以取值为关键字default, primary, success, warning, 以及其他支持的CSS颜色值

```html
<template>
    <span>333</span>
</template>
```
:::

### 使用icon展示时间点

::: demo icon的默认大小将改为13px * 13px大小，颜色受v-timeline-item组件的color属性影响，也可以自定义

```html
<template>
    <span>222</span>
</template>
```
:::

### 带虚线尾巴的时间线

::: demo 当遇到时间线未全部展示完全的场景时，可以通过设置'pending'属性为true，来产生最后一个带有虚线延长的时间线

```html
<template>
    <span>111</span>
</template>
```
:::

### Timeline属性

| 参数      | 说明                             | 类型      | 可选值       | 默认值 |
| -------- | -------------------------------- | -------- | ----------- | ----- |
| pending  |  是否未完待续（最后一个时间点为延长虚线） | Boolean |  true  | false |

### TimelineItem属性

| 参数      | 说明                             | 类型      | 可选值       | 默认值 |
| -------- | -------------------------------- | -------- | ----------- | ----- |
| color  | 时间节点或icon颜色 | String |  'default', 'primary', 'success', 'warning', 以及其他支持的CSS颜色值  | 'default' |

### TimelineItem Slot

| Slot名称  | 说明                             |
| -------- | -------------------------------- |
|  icon  |         替代时间节点的展示         |

### 自定义事件

| 事件名称  | 说明                              | 事件参数  |
| -------  | -------------------------------- | -------- |
|          |                                  |          |


### 方法
| 方法名称   | 说明                             | 参数  |
| -------  | -------------------------------- | -------- |
|          |                                  |          |


`

it's my .md file

**Comment by Blubiubiu** [comment]
when i remove <script> and <style>, it is well

**Comment by Blubiubiu** [comment]
i can't use <script> on the top

**Comment by Blubiubiu** [comment]
if somemethod support me to use <script> on the top?

**Comment by wxsms** [comment]
no. you can't. for now.

**Comment by Blubiubiu** [comment]
becauseof vue-loader or markdownIt?

**Comment by Blubiubiu** [comment]
but when i use webpackv4.x and vue-loader@14.x.x, it is worked!!!

**Comment by Blubiubiu** [comment]
thks 4 ur apply, I close isuues

**Comment by wxsms** [comment]
welcome, this plugin have not consider top level script/style usage, so it's not garantee if it works or not. but glads that your problem have been solved.
