### ISSUE TITLE
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

### ISSUE THREAD

**Issue by Gilbert5210** [wxsms/vue-md-loader#383]
当我在md文件上写vue代码的时候，发现他会报错
我的写法：

index.md
```
## test
<template></template>
<script></script>
```

错误：
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

请问怎么解决，我看[vue-markdown-loader](https://github.com/QingWei-Li/vue-markdown-loader)这个是可以渲染的

**Comment by wxsms** [comment]
please use [vue-markdown-loader](https://github.com/QingWei-Li/vue-markdown-loader) instead

**Comment by Gilbert5210** [comment]
@wxsms 
现在https://github.com/QingWei-Li/vue-markdown-loader存在另外一个打包的问题没解决，也是不能使用的

我就想问问，我们是否兼容再md文件里面写vue模板的操作？
如何配置？

**Comment by wxsms** [comment]
目前不支持。本loader支持的方式请参考示例项目。
